options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-east1
  _SERVICE: qa-reto-summer-pde-2026-frontend
  _AR_REPO: reto-summer-pde-2026
  _IMAGE: qa-reto-summer-pde-2026-frontend
  _API_BASE_URL: https://qa-reto-summer-pde-2026-invenzis-backend-133459896240.us-east1.run.app

steps:
  # Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA
      - API_BASE_URL=${_API_BASE_URL}
      - .

  # Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA

  # Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA
